"""Alumnos con cambios en los campos

Revision ID: 943c62e5b999
Revises: 023cddc598e4
Create Date: 2026-02-25 20:21:58.702648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943c62e5b999'
down_revision = '023cddc598e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
