"""Creacion tabla maestros

Revision ID: dd6d27cf1fb5
Revises: a44090462f27
Create Date: 2026-02-26 17:29:19.609553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6d27cf1fb5'
down_revision = 'a44090462f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maestros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('apellidos', sa.String(length=120), nullable=True),
    sa.Column('especialidad', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maestros')
    # ### end Alembic commands ###
